# example script for pulling in .vcf files generated by simulations and extracting the allelic richness and observed heterozygosity.

library(vcfR)
library(adegenet)
library(dartR)
#library(dplyr)


## PULL DATA IN##
filesM <- list.files(path="C:/OUTPUT FILE LOCATION",pattern="PREFIX OF FILENAME_" )

gls <- list()

d<-function(i)
{
  dumvcf<- read.vcfR(file.path("C:/OUTPUT FILE LOCATION",filesM[i]),verbose=FALSE)
  gls<- vcfR2genlight(dumvcf)
  namesgls <- filesM[i]  
  locd <- data.frame(mig = NA, mev = NA, pNum=NA, Lnum=NA, het=NA, rep=NA, gen=NA)# SET UP COLUMN HEADINGS FOR DATAFRAME
  cc <-1
  pNum<-as.numeric(gsub("PREFIX_([0-9]+).*$", "\\1",namesgls))#THESE WILL DEPEND ON THE NAMING CONVENTION USED FOR .VCF FILES
  rep<-as.numeric(gsub(".*?_rep_([0-9]+).*$","\\1", namesgls))
  mig<-as.numeric(gsub(".*?_mig_([0-9]+).*$","\\1", namesgls))
  mev<-as.numeric(gsub(".*?_mev([0-9]+).*$","\\1", namesgls))
  gen<-as.numeric(gsub(".*?_gen([0-9]+).*$","\\1", namesgls))
  nind<-nInd(gls)
  het<-sum(as.matrix(gls)==1)/(nind*1*200)
  glout<-gl.filter.monomorphs(gls, verbose = 0)
  Lnum<-(2*nLoc(glout)) + (200-nLoc(glout))
  locd[cc,]<-rbind(c(mig, mev, pNum, Lnum, het, rep, gen)) 
  cc<-cc+1
  return(locd)
  
}

system.time(locd <- mclapply(1:length(filesM), function(x) d(x), mc.cores = 1))

DATA<-do.call(rbind.data.frame,locd)

#write to csv and create plots using ggplot2